export const SET_LEAGUE_STANDINGS = 'SET_LEAGUE_STANDINGS';
export const SET_HEADER_VISIBILITY = 'SET_HEADER_VISIBILITY';
export const SET_LAST_MATCH_DETAILS = 'SET_LAST_MATCH_DETAILS';
export const SET_PRICES_SEEN_STATE = 'SET_PRICES_SEEN_STATE';
