export default {
  // Needs to move to a api
  getLeagueResults(day) {
    switch (day) {
      case 'tuesday':

        return [
          {
            player: 'Sageeth',
            played: 8,
            won: 6,
            draw: 0,
            lost: 2,
            ps: 2,
            doOut: 0,
            late: 0,
            votes: 23,
            mom: 3,
            total: 0,
            ave: 0,
          },
          {
            player: 'Arun',
            played: 2,
            won: 1,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Millen',
            played: 8,
            won: 5,
            draw: 0,
            lost: 3,
            ps: 0,
            doOut: 0,
            late: 1,
            votes: 22,
            mom: 2,
            total: 0,
            ave: 0,
          },
          {
            player: 'Av',
            played: 8,
            won: 5,
            draw: 0,
            lost: 3,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 5,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Tony',
            played: 9,
            won: 4,
            draw: 0,
            lost: 5,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 9,
            mom: 1,
            total: 0,
            ave: 0,
          },
          {
            player: 'Brinthan',
            played: 6,
            won: 3,
            draw: 0,
            lost: 3,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 11,
            mom: 1,
            total: 0,
            ave: 0,
          },
          {
            player: 'Sri',
            played: 7,
            won: 4,
            draw: 0,
            lost: 3,
            ps: 0,
            doOut: 0,
            late: 2,
            votes: 2,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Brana',
            played: 8,
            won: 4,
            draw: 0,
            lost: 4,
            ps: 0,
            doOut: 0,
            late: 0,
            mom: 0,
            votes: 9,
            total: 0,
            ave: 0,
          },
          {
            player: 'Muz',
            played: 8,
            won: 4,
            draw: 0,
            lost: 4,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Kevin',
            played: 6,
            won: 3,
            draw: 0,
            lost: 3,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 1,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'German',
            played: 5,
            won: 4,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 1,
            votes: 5,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Mayu',
            played: 6,
            won: 3,
            draw: 0,
            lost: 3,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Theepan',
            played: 5,
            won: 2,
            draw: 0,
            lost: 3,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 5,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Ben',
            played: 5,
            won: 3,
            draw: 0,
            lost: 2,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 5,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Slim',
            played: 2,
            won: 1,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 9,
            mom: 1,
            total: 0,
            ave: 0,
          },
          {
            player: 'Sat',
            played: 6,
            won: 1,
            draw: 0,
            lost: 5,
            ps: 0,
            doOut: 1,
            late: 0,
            votes: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Nivi',
            played: 4,
            won: 1,
            draw: 0,
            lost: 3,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 3,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'James',
            played: 3,
            won: 2,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Ashok',
            played: 2,
            won: 1,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 3,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Vanid',
            played: 2,
            won: 1,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 1,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Lucky',
            played: 2,
            won: 1,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Brandon',
            played: 3,
            won: 1,
            draw: 0,
            lost: 2,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 8,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Gracie',
            played: 2,
            won: 1,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 2,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Prav',
            played: 1,
            won: 0,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Avi',
            played: 1,
            won: 1,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            total: 0,
            ave: 0,
          }];

      case 'thursday':
        return [
          {
            player: 'Redon',
            played: 1,
            won: 0,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Gracie',
            played: 1,
            won: 0,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Brandon',
            played: 1,
            won: 0,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Crouch',
            played: 1,
            won: 0,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Kelly',
            played: 1,
            won: 0,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Sat',
            played: 1,
            won: 0,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Rob',
            played: 1,
            won: 0,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Turner',
            played: 1,
            won: 0,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Ben',
            played: 1,
            won: 0,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Leigh',
            played: 1,
            won: 0,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Kurt',
            played: 1,
            won: 0,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Muz',
            played: 1,
            won: 0,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            total: 0,
            ave: 0,
          }];

      default:
        break;
    }

    return false;
  },

  getLastMatchDetails(day) {
    switch (day) {
      case 'tuesday':

        return [
          {
            teamOne: [
              'BLACKS ⚫',
              'Sageeth',
              'James',
              'Ben',
              'Arun',
              'Muz',
              'Mayu',
              'Brana',
            ],
            teamTwo: [
              'REDS 🔴',
              'Millen',
              'Brandon',
              'Tony',
              'Nivi',
              'German',
              'Sat',
              'Prav',
            ],
            mom: [
              'Not published yet',
            ],
            fines: [],
            finalScore: '7 - 0 to Blacks',
            matchNumber: 10,
          }];

      case 'thursday':
        return [
          {
            teamOne: [
              'BLACKS ⚫',
              'Redon',
              'Gracie',
              'Brandon',
              'Crouch',
              'Kelly',
              'Sat',
            ],
            teamTwo: [
              'WHITES ⚪',
              'Rob',
              'Turner',
              'Ben',
              'Leigh',
              'Kurt',
              'Muz',
            ],
            mom: [
              'Not Published',
            ],
            fines: [],
            finalScore: 'Not published',
            matchNumber: 1,
          }];

      default:
        break;
    }

    return false;
  },
};
