export default {
  // Needs to move to a api
  getLeagueResults(day) {
    switch (day) {
      case 'tuesday':

        return [
          {
            player: 'Tivyan',
            played: 1,
            won: 0,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Kevin Na',
            played: 1,
            won: 1,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 1,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Arun',
            played: 1,
            won: 1,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 10,
            mom: 1,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Nivi',
            played: 1,
            won: 1,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Mini',
            played: 1,
            won: 1,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 8,
            mom: 1,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Kannan',
            played: 2,
            won: 1,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 3,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Sri',
            played: 2,
            won: 1,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 1,
            votes: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Sageeth',
            played: 2,
            won: 0,
            draw: 0,
            lost: 2,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Av',
            played: 4,
            won: 4,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Gin',
            played: 3,
            won: 3,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 1,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Mayu',
            played: 4,
            won: 2,
            draw: 0,
            lost: 2,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 1,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Millen',
            played: 3,
            won: 1,
            draw: 0,
            lost: 2,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 11,
            mom: 0,
            momSplit: 2,
            total: 0,
            ave: 0,
          },
          {
            player: 'Muz',
            played: 4,
            won: 2,
            draw: 0,
            lost: 2,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 2,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Kevin',
            played: 4,
            won: 2,
            draw: 0,
            lost: 2,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Ashok',
            played: 1,
            won: 1,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 7,
            mom: 0,
            momSplit: 1,
            total: 0,
            ave: 0,
          },
          {
            player: 'Brana',
            played: 4,
            won: 1,
            draw: 0,
            lost: 3,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Kash',
            played: 1,
            won: 0,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Brinthan',
            played: 4,
            won: 2,
            draw: 0,
            lost: 2,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Ben',
            played: 4,
            won: 1,
            draw: 0,
            lost: 3,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Brandon',
            played: 3,
            won: 2,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 6,
            mom: 0,
            momSplit: 1,
            total: 0,
            ave: 0,
          },
          {
            player: 'Tony',
            played: 4,
            won: 1,
            draw: 0,
            lost: 3,
            ps: 0,
            doOut: 0,
            late: 0,
            votes: 5,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Sat',
            played: 2,
            won: 0,
            draw: 0,
            lost: 2,
            ps: 0,
            doOut: 1,
            late: 0,
            votes: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          }];

      case 'thursday':
        return [
          {
            player: 'Redon',
            played: 1,
            won: 1,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Gracie',
            played: 1,
            won: 1,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 1,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Brandon',
            played: 1,
            won: 1,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Crouch',
            played: 1,
            won: 1,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Kelly',
            played: 1,
            won: 1,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Sat',
            played: 1,
            won: 1,
            draw: 0,
            lost: 0,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Rob',
            played: 1,
            won: 0,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Turner',
            played: 1,
            won: 0,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Ben',
            played: 1,
            won: 0,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Leigh',
            played: 1,
            won: 0,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Kurt',
            played: 1,
            won: 0,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          },
          {
            player: 'Muz',
            played: 1,
            won: 0,
            draw: 0,
            lost: 1,
            ps: 0,
            doOut: 0,
            loy: 0,
            late: 0,
            mom: 0,
            momSplit: 0,
            total: 0,
            ave: 0,
          }];

      default:
        break;
    }

    return false;
  },

  getLastMatchDetails(day) {
    switch (day) {
      case 'tuesday':

        return [
          {
            teamOne: [
              'BLACKS ⚫',
              'Brana',
              'Mayu',
              'Tivyan',
              'Tony',
              'Millen',
              'Kev',
              'Muz',
            ],
            teamTwo: [
              'REDS 🔴',
              'Av',
              'Gin',
              'Kevin Na',
              'Brandon',
              'Kannan',
              'Ben',
              'Brinthan',
            ],
            mom: [
              'Brandon & Millen (Votes 4 each) - 👏',
            ],
            fines: [],
            dropOuts: ['Sat'],
            finalScore: '12-16 - Reds Win',
            matchNumber: 4,
          }];

      case 'thursday':
        return [
          {
            teamOne: [
              'BLACKS ⚫',
              'Redon',
              'Gracie',
              'Brandon',
              'Crouch',
              'Kelly',
              'Sat',
            ],
            teamTwo: [
              'WHITES ⚪',
              'Rob',
              'Turner',
              'Ben',
              'Leigh',
              'Kurt',
              'Muz',
            ],
            mom: [
              'Gracie',
            ],
            fines: [],
            finalScore: '2 - 0 to Blacks',
            matchNumber: 1,
          }];

      default:
        break;
    }

    return false;
  },
};
